---
- hosts: all
  connection: local

  vars_files:
    - vars.yml

  pre_tasks:
    - name: "Update apt cache if needed."
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: true

    - name: "Install aptitude - preferred for ansible"
      apt:
        state: latest
        name:
          - aptitude
      become: true

    - name: "Update all packages to the latest version"
      apt:
        upgrade: dist
      become: true

  tasks:
    - name: "Install apt cmd line apps"
      apt:
        state: latest
        name:
          - awscli
          - dos2unix
          - gnupg
          - golang
          - graphviz
          - jq
          - libsqlite3-dev
          - mlocate
          - neofetch
          - net-tools
          - nmap
          - silversearcher-ag
          - tree
          - unzip
          - zip
      become: true

    - include_tasks: tasks/yarn.yml
      when: install_yarn

    - include_tasks: tasks/tfenv.yml
      when: install_tfenv

    - include_tasks: tasks/aws-vault.yml
      when: install_aws_vault

    - include_tasks: tasks/rbenv.yml
      when: install_rbenv

    - include_tasks: tasks/kubectl.yml
      when: install_kubectl

    - include_tasks: tasks/eksctl.yml
      when: install_eksctl
    
    - include_tasks: tasks/helm.yml
      when: install_helm

  post_tasks:
    - name: "apt autoclean && autoremove"
      apt:
        autoclean: yes
        autoremove: yes
      become: true

    - name: "clean up /tmp"
      file:
        path: /tmp/*
        state: absent
      become: true

  roles:
    - role: stephdewit.nvm
      nvm_version: 0.37.2
      nvm_node_version: 14.15.5
      become: false
