
- name: "helm download  & install {{ helm['version'] }}"
  get_url:
    url: "https://get.helm.sh/helm-{{ helm['version'] }}-linux-amd64.tar.gz"
    dest: "/tmp"
    checksum: "{{ helm['checksum'] }}"
    mode: '0755'
  become: true

- name: "Extract helm package"
  unarchive:
    src: "/tmp/helm-{{ helm['version'] }}-linux-amd64.tar.gz"
    dest: "/tmp"
  become: true

- name: "Install Helm"
  shell: 'mv /tmp/linux-amd64/helm /usr/local/bin'
  become: true

- name: "Add official repo to Helm"
  shell: 'helm repo add stable https://charts.helm.sh/stable'
